version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6378:6379
    volumes:
      - data:/data
    container_name: cache
    command: redis-server --save 20 1 --loglevel warning --requirepass 1234
    networks:
      - work
  db:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 2716:27017
    networks:
      - work
  staff:
    build: ./staff
    volumes:
      - ./staff:/app/staff
    ports:
      - 3333:3333
    depends_on:
      - redis
      - db
    links:
      - db
      - redis
    environment:
      URL_MongoDB: "mongodb://db:27017"
      REDIS_URL: "cache:6379"
      REDIS_PASSWORD: "1234"
      Port: "3333"
      PortTeam: "http://localhost:3334/"
    networks:
      - work
  team:
    build: ./team
    volumes:
      - ./team:/app/team
    ports:
      - 3334:3334
    depends_on:
      - redis
      - db
    links:
      - db
      - redis
    environment:
      URL_MongoDB: "mongodb://db:27017"
      REDIS_URL: "cache:6379"
      REDIS_PASSWORD: "1234"
      Port: "3334"
      PortStaff: "http://localhost:3333/"
    networks:
      - work
  fe:
    build: ./staff-team
    volumes:
      - ./staff-team:/app
      - /app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - staff
      - team
    environment:
      VUE_APP_TEAM: http://10.3.145.14:3334/
      VUE_APP_STAFF: http://10.3.145.14:3333/
    networks:
      - work
networks:
  work:
    name: work
volumes:
  mongodb:
  mongodb_config:
  data:
